<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'slug' => 'home',
                'title' => 'Home',
                'subtitle' => 'Climate resilience, environmental stewardship, and citizen action rooted in Tacloban City.',
                'hero_eyebrow' => 'Rooted in Resilience. Rising for Tomorrow',
                'hero_title' => 'BUILDING RESILIENT COMMUNITIES',
                'hero_subtitle' => null,
                'hero_image' => '/images/hero/mangrove-river-hero.jpg',
                'meta_title' => 'PH Haiyan Advocacy Inc. | Climate Resilience and Environmental Advocacy',
                'meta_description' => 'Learn about PH Haiyan Advocacy Inc., its mission, public letters, forums, tree-growing initiatives, and climate resilience work in Tacloban and Eastern Visayas.',
                'content' => [
                    'hero_title_lines' => ['Building', 'Resilient', 'Communities'],
                    'hero_intro' => 'Community-led advocacy for climate resilience, environmental protection, and public accountability in Tacloban City and Eastern Visayas.',
                    'hero_tagline' => null,
                    'hero_chips' => ['Envision', 'Engage', 'Empower'],
                    'hero_teaser' => [
                        'eyebrow' => 'Updates',
                        'title' => 'Latest news and recent activity.',
                        'actions' => [
                            ['label' => 'News', 'href' => '#latest-updates'],
                            ['label' => 'Activities', 'href' => '#recent-activities'],
                        ],
                    ],
                    'hero_stats' => [
                        ['value' => '2013', 'label' => 'established in the aftermath of Typhoon Haiyan'],
                        ['value' => 'Tacloban City', 'label' => 'local focus shaped by lived experience'],
                        ['value' => 'Eastern Visayas', 'label' => 'regional horizon for resilience work'],
                    ],
                    'mission_pillars' => [
                        [
                            'icon' => 'eye',
                            'title' => 'Envision',
                            'description' => 'We advance a long-view vision of Tacloban as a model city for climate resilience, climate-smart planning, and greener public spaces.',
                        ],
                        [
                            'icon' => 'users',
                            'title' => 'Engage',
                            'description' => 'We bring citizens, schools, civic groups, and agencies into public dialogue through forums, letters, and community-facing advocacy.',
                        ],
                        [
                            'icon' => 'sprout',
                            'title' => 'Empower',
                            'description' => 'We turn concern into action through tree-growing, watershed and bay protection, flood-control advocacy, and practical environmental education.',
                        ],
                    ],
                    'about_preview' => [
                        'heading' => 'Born from recovery. Focused on long-term resilience.',
                        'image' => '/images/imported/gallery/first-interagency-meeting.jpg',
                        'body' => [
                            'PH Haiyan Advocacy Inc. is a community-based organization focused on climate resilience and environmental protection. Established after Typhoon Yolanda in 2013, our work begins in Tacloban City.',
                            'We aim to build Tacloban as a model of climate resilience, setting a standard that can guide other communities. Through environmental restoration, disaster preparedness, and policy advocacy, we turn this vision into action.',
                            'We believe real change happens when communities are informed, involved, and empowered.',
                        ],
                    ],
                    'impact_cta' => [
                        'title' => 'Be part of a more resilient tomorrow.',
                        'description' => 'Support the people and programs behind tree-growing, flood-control advocacy, community forums, watershed protection, and public-interest environmental work.',
                        'background_image' => '/images/hero/mangrove-river-bright.jpg',
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'about-ph-haiyan',
                'title' => 'About PH Haiyan',
                'subtitle' => 'The history, mission, people, and public purpose behind PH Haiyan Advocacy Inc.',
                'hero_eyebrow' => 'About PH Haiyan',
                'hero_title' => 'Building climate resilience from Tacloban outward.',
                'hero_subtitle' => 'PH Haiyan Advocacy Inc. is a community-based organization focused on climate resilience, environmental protection, and public action shaped by the experience of Typhoon Yolanda.',
                'hero_image' => '/images/imported/floodcontrol/flood-control-forum.jpg',
                'meta_title' => 'About PH Haiyan Advocacy Inc.',
                'meta_description' => 'Learn who PH Haiyan Advocacy Inc. is, what its logo represents, how it began after Typhoon Yolanda, and why climate resilience matters for Tacloban.',
                'content' => [
                    'who_we_are' => [
                        'PH Haiyan Advocacy Inc. is a community-based organization focused on climate resilience and environmental protection. Established after Typhoon Yolanda in 2013, our work begins in Tacloban City.',
                        'We aim to build Tacloban as a model of climate resilience, setting a standard that can guide other communities. Through environmental restoration, disaster preparedness, and policy advocacy, we turn this vision into action.',
                        'We believe real change happens when communities are informed, involved, and empowered.',
                    ],
                    'logo' => [
                        'The PH Haiyan Advocacy Inc. logo represents our commitment to environmental protection, climate resilience, and community empowerment.',
                        'The water droplet symbolizes life and our connection to vital ecosystems such as watersheds and coastal areas. The leaf at its center reflects growth, sustainability, and our dedication to ecological restoration.',
                        'Green represents nature and sustainable development, while blue signifies trust, transparency, and our advocacy for water conservation and disaster preparedness.',
                        'Together, these elements express our vision of communities and nature working in harmony: resilient, empowered, and prepared for the future.',
                    ],
                    'ceo' => [
                        'name' => 'Pete L. Ilagan',
                        'role' => 'CEO, PH Haiyan Advocacy Inc.',
                        'description' => 'Leading PH Haiyan with a civic, environmental, and resilience-centered vision for Tacloban and Eastern Visayas.',
                        'image' => '/uploads/about/ceo-pete-ilagan.png',
                        'highlights' => [
                            'Pete L. Ilagan helped shape PH Haiyan from a citizen-led response into a long-view climate resilience advocacy rooted in Tacloban.',
                            'As a survivor of Super Typhoon Haiyan and a long-time conservation advocate, he pushed for practical environmental rehabilitation when local climate-response plans were still missing.',
                            'His leadership helped gather professionals, advocates, and community partners around a shared goal: building systems that make Tacloban and Eastern Visayas more prepared for future climate threats.',
                        ],
                    ],
                    'mission_vision' => [
                        'eyebrow' => 'Mission and Vision',
                        'heading' => "The principles guiding PH Haiyan's work in Tacloban and Eastern Visayas.",
                        'description' => "These statements define the organization's present responsibility and the future it is working to help shape.",
                        'badge' => 'Core Direction',
                        'background_image' => '/images/imported/events/event-balugo-watershed.jpg',
                        'mission_label' => 'Mission',
                        'mission_title' => 'What PH Haiyan is called to do now.',
                        'mission_quote' => 'Overcoming climate threats by building resilient interdependent systems in Tacloban City and across Eastern Visayas, Philippines.',
                        'vision_label' => 'Vision',
                        'vision_title' => 'What PH Haiyan is working toward.',
                        'vision_quote' => 'A future where Tacloban City stands as a model for climate resilience and climate-smart development in the Philippines.',
                    ],
                    'story' => [
                        'PH Haiyan Advocacy Inc. was established in the aftermath of Typhoon Haiyan, locally known as Yolanda, one of the strongest typhoons ever to make landfall in recorded history. With winds exceeding 300 km/h and a powerful storm surge, it devastated large parts of Eastern Visayas, with Tacloban City at the center of destruction.',
                        'Surrounded by water on three sides, Tacloban was overwhelmed by massive flooding. Thousands of lives were lost, homes were destroyed, and entire communities were wiped out. The scale of devastation drew global attention, bringing international media, humanitarian aid, and scientific experts. Many warned that because of climate change, such extreme weather events could become the new normal.',
                        'Amid this reality, Pete L. Ilagan, a survivor and long-time environmental advocate, recognized the urgent need for action. Upon engaging with local authorities, he found that there were no clear plans for environmental rehabilitation or climate resilience.',
                        'Determined to respond, he brought together fellow survivors, professionals, and advocates from various sectors, including academe, law, health, and faith-based groups. With the support of experts such as Eulito V. Casas Jr., a core group was formed, united by a shared mission to build safer, more resilient communities.',
                        'In 2015, the organization was formally established as an advocacy cooperative and registered with the Cooperative Development Authority. At present, PH Haiyan Advocacy Inc. remains committed to transforming Tacloban into a model city for climate resilience by strengthening environmental protection, disaster preparedness, and community capacity in the face of a changing climate.',
                    ],
                    'why_resilience' => [
                        'heading' => 'Why climate resilience matters for Tacloban',
                        'paragraphs' => [
                            'Tacloban City has become a symbol of both vulnerability and resilience after Typhoon Haiyan. The disaster revealed the urgent need for practical, science-based solutions to climate risks.',
                            'Climate resilience means building communities that are prepared, adaptive, and sustainable, able to withstand and recover from storms, flooding, and rising seas.',
                            'PH Haiyan Advocacy envisions Tacloban as a model for climate resilience. We work with communities, experts, and government to promote sustainable solutions, resilient infrastructure, and a culture of preparedness.',
                            'By setting this example, we aim to inspire other vulnerable communities, because no city should endure the same level of devastation again.',
                        ],
                    ],
                    'cta' => [
                        'heading' => 'Support a more resilient future for Tacloban.',
                        'description' => 'Whether you want to volunteer, donate, partner, or simply learn more, there is room to stand with PH Haiyan in building safer and more prepared communities.',
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'what-we-do',
                'title' => 'What We Do',
                'subtitle' => 'Programs, campaigns, and public actions shaping a climate-resilient Tacloban.',
                'hero_eyebrow' => 'What We Do',
                'hero_title' => "Turning Tacloban's climate resilience vision into public action.",
                'hero_subtitle' => 'PH Haiyan works through environmental restoration, disaster preparedness, policy advocacy, and community empowerment to help shape Tacloban as a model for climate resilience.',
                'hero_image' => '/images/imported/news/launching-tree-planting-plan.png',
                'meta_title' => 'What We Do | PH Haiyan Advocacy Inc.',
                'meta_description' => "Explore PH Haiyan's climate resilience work in environmental restoration, preparedness, policy advocacy, public education, and community empowerment.",
                'content' => [
                    'intro' => [
                        'PH Haiyan Advocacy Inc. is a community-based organization focused on climate resilience and environmental protection. Established after Typhoon Yolanda in 2013, the work begins in Tacloban City and is shaped by the lessons of post-disaster recovery.',
                        'The organization aims to help build Tacloban as a model of climate resilience by combining environmental restoration, disaster preparedness, policy advocacy, and public participation in one practical advocacy platform.',
                        'PH Haiyan believes real change happens when communities are informed, involved, and empowered. Its programs therefore connect citizens, students, experts, local leaders, and partner institutions around visible resilience work.',
                    ],
                    'initiatives' => [
                        [
                            'icon' => 'leaf',
                            'title' => 'Environmental Restoration',
                            'description' => 'PH Haiyan advances mangrove rehabilitation, tree-growing, nursery support, and ecological restoration work that helps protect coastlines, watersheds, and public green spaces.',
                        ],
                        [
                            'icon' => 'shield',
                            'title' => 'Climate Resilience',
                            'description' => 'The organization promotes preparedness, adaptive planning, and practical resilience measures so Tacloban can better withstand flooding, storm surge, and other climate risks.',
                        ],
                        [
                            'icon' => 'megaphone',
                            'title' => 'Policy Advocacy',
                            'description' => 'Forums, letters, and direct engagement with agencies are used to press for science-based flood control, transparent planning, and timely government action.',
                        ],
                        [
                            'icon' => 'users',
                            'title' => 'Community Empowerment',
                            'description' => 'Work stays community-based by involving residents, volunteers, partner groups, and civic leaders in discussions, site activities, and public problem-solving.',
                        ],
                        [
                            'icon' => 'spark',
                            'title' => 'Youth Climate Leadership',
                            'description' => 'PH Haiyan invests in the next generation through student forums, climate conferences, and public education that help young people become informed environmental advocates.',
                        ],
                        [
                            'icon' => 'sprout',
                            'title' => 'Watershed and Coastal Stewardship',
                            'description' => 'The advocacy links water systems, coastal protection, and long-term land care through watershed proposals, coastal restoration, and climate learning initiatives.',
                        ],
                    ],
                    'stats' => [
                        ['value' => '2013', 'label' => 'work begins after Typhoon Yolanda'],
                        ['value' => '46 hectares', 'label' => 'mangrove reforestation proposed with DENR'],
                        ['value' => '250 students', 'label' => 'gathered in the first regional climate conference'],
                        ['value' => '200 people', 'label' => 'target capacity for the resiliency learning center'],
                    ],
                    'stories' => [
                        [
                            'title' => '46-hectare mangrove reforestation along the Tacloban coastline',
                            'description' => "In 2017, PH Haiyan helped bring its resilience vision into action through a 46-hectare mangrove reforestation effort developed with DENR as nature's front line against storm surge.",
                        ],
                        [
                            'title' => 'Regional Conference on Climate Adaptation and Mitigation',
                            'description' => 'The organization convened college students from State Universities across Region 8 to help build a new generation of climate advocates and informed resilience leaders.',
                        ],
                        [
                            'title' => 'Flood Control Mitigation Forum and Manifesto of Commitment',
                            'description' => 'After renewed flooding threats in late 2024, PH Haiyan helped convene a public forum that pressed for flood-control review and secured a shared commitment toward a flood-free Tacloban.',
                        ],
                    ],
                    'project_archive' => [
                        [
                            'slug' => 'project-1-nursery-seedling-production',
                            'title' => 'Project 1. Nursery Seedling Production',
                            'summary' => 'PH Haiyan purchased mangrove seedlings from barangay nurseries so coastal planting could move quickly while keeping local growers involved.',
                            'description' => 'The old website records that, because of limited project time, PH Haiyan purchased mangrove seedlings from BLGUs instead of waiting for a longer nursery cycle. In Barangay Tagpuro, Tacloban City, the project worked with the barangay nursery and purchased seedlings at PHP 10.00 per piece, with every planted seedling also carrying a PHP 2.00 planting payment. The approach helped cover 7.8 hectares of coastline while giving local nursery growers and residents a direct role in restoration work.',
                            'image' => '/images/imported/projects/project-1-nursery-seedling-production.jpg',
                        ],
                        [
                            'slug' => 'project-2-mangrove-reforestation',
                            'title' => 'Project 2. Mangrove Reforestation',
                            'summary' => 'DENR-certified survival rates and large-scale planting turned mangrove restoration into one of PH Haiyan\'s clearest environmental interventions.',
                            'description' => 'The old website records that as of September 2018, DENR certified a 90% survival rate for the mangroves planted in the project\'s reforestation sites. It reports that 39.50 hectares were enhanced, around 50 hectares were covered across six barangays, approximately 460,000 seedlings were planted from November 2017 to September 2018, and about 5.8 kilometers of planting areas were fenced with fishnets to protect the sites from natural and human disturbance.',
                            'image' => '/images/imported/projects/project-2-mangrove-reforestation.jpg',
                        ],
                        [
                            'slug' => 'project-3-livelihood-projects-and-opportunities',
                            'title' => 'Project 3. Livelihood Projects and Opportunities',
                            'summary' => 'Livelihood support was tied directly to coastal management, site preparation, and hands-on mangrove protection work.',
                            'description' => 'According to the old website, PH Haiyan provided livelihood assistance to selected beneficiaries while focusing on coastal management and mangrove protection. The project purchased community-available materials such as bamboo stakes and supplies used to protect planting areas from debris. Residents within the project site were employed for site preparation, clean-up, fencing, netting, and staking, helping strengthen both ownership and participation in the reforestation effort.',
                            'image' => '/images/imported/projects/project-3-livelihood-opportunities.jpg',
                        ],
                        [
                            'slug' => 'project-4-mainstreaming-climate-change-adaptation',
                            'title' => 'Project 4. Mainstreaming of Climate Change Adaptation',
                            'summary' => 'Public orientations and consultations helped bring climate adaptation into schools, agencies, and coastal communities.',
                            'description' => 'The old website describes this project as a public-facing effort to mainstream climate change adaptation and encourage broader support for resilience work. PH Haiyan conducted orientations in academic institutions, government agencies, and coastal barangays to raise awareness and build backing for climate-mitigation initiatives. It also held consultative meetings with fisherfolk and people\'s organizations so adaptation work would be grounded in the actual concerns of affected communities.',
                            'image' => '/images/imported/projects/project-4-mainstreaming-climate-adaptation.jpg',
                        ],
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'projects',
                'title' => 'Projects',
                'subtitle' => 'Legacy project records and environmental initiatives organized from the original PH Haiyan website.',
                'hero_eyebrow' => 'Projects',
                'hero_title' => 'Project records that show how the advocacy became visible on the ground.',
                'hero_subtitle' => 'This page organizes PH Haiyan’s older project portfolio into a cleaner archive covering mangrove restoration, livelihood support, climate education, policy advocacy, and watershed planning.',
                'hero_image' => '/images/imported/projects/legacy/4d.jpg',
                'meta_title' => 'Projects | PH Haiyan Advocacy Inc.',
                'meta_description' => "Browse PH Haiyan's legacy projects and initiatives, including mangrove restoration, climate conferences, policy work, nursery development, and watershed planning.",
                'content' => [
                    'intro' => [
                        'This page gathers the project records previously published on PH Haiyan’s original What We Do page and reorganizes them into one cleaner project directory.',
                        'Together these records show how the advocacy moved from post-Haiyan recovery into practical work: mangrove planting, livelihood support, climate orientations, youth conferences, policy lobbying, beach forest recovery, nursery development, and watershed planning.',
                        'Use the directory below to search by title or filter by theme, then open each project to review the full legacy record preserved from the original website.',
                    ],
                    'projects' => [
                        [
                            'slug' => 'project-1-nursery-seedling-production',
                            'title' => 'Project 1. Nursery Seedling Production',
                            'category' => 'Coastal Restoration',
                            'year' => '2017',
                            'summary' => 'PH Haiyan purchased mangrove seedlings from barangay nurseries so coastal planting could begin quickly while keeping local growers involved.',
                            'description' => 'Because implementation time was limited, PH Haiyan sourced seedlings from barangay and local government nurseries instead of waiting for a longer nursery cycle. In Barangay Tagpuro, Tacloban City, the project arranged the purchase of 8,333 seedlings per hectare to cover 7.8 hectares of coastline. Each seedling planted also carried a planting payment, and fisherfolk made up the majority of planters. Women were deliberately encouraged to participate as part of the project’s gender-inclusive approach.',
                            'image' => '/images/imported/projects/legacy/1.jpg',
                        ],
                        [
                            'slug' => 'project-2-mangrove-reforestation',
                            'title' => 'Project 2. Mangrove Reforestation',
                            'category' => 'Coastal Restoration',
                            'year' => '2018',
                            'summary' => 'DENR-certified survival rates and large-scale planting made mangrove restoration one of PH Haiyan’s clearest environmental interventions.',
                            'description' => 'As recorded on the original site, DENR certified a 90% survival rate for the mangroves planted in the project’s reforestation sites as of September 2018. The archive reports 39.50 hectares enhanced, around 50 hectares covered across six barangays, and approximately 460,000 seedlings planted from November 2017 to September 2018. To protect planting areas from natural and human disturbance, the project also fenced around 5.8 kilometers of sites using fishnets.',
                            'image' => '/images/imported/projects/legacy/2.jpg',
                        ],
                        [
                            'slug' => 'project-3-livelihood-projects-and-opportunities',
                            'title' => 'Project 3. Livelihood Projects and Opportunities',
                            'category' => 'Livelihood Support',
                            'year' => null,
                            'summary' => 'Livelihood assistance was tied directly to coastal management, site preparation, and hands-on mangrove protection work.',
                            'description' => 'PH Haiyan provided livelihood assistance to selected beneficiaries while focusing on coastal management and mangrove protection. The project purchased community-available materials such as bamboo stakes that could be used in mangrove development and reforestation. Residents within the project site were employed for clean-up, fencing, netting, and staking, helping deepen participation and build a stronger sense of ownership within the community.',
                            'image' => '/images/imported/projects/legacy/3.jpg',
                        ],
                        [
                            'slug' => 'project-4-mainstreaming-climate-change-adaptation',
                            'title' => 'Project 4. Mainstreaming of Climate Change Adaptation',
                            'category' => 'Climate Education',
                            'year' => null,
                            'summary' => 'Project orientations and consultations helped bring climate adaptation into schools, agencies, and coastal barangays.',
                            'description' => 'To mainstream climate change adaptation and encourage wider public support, the project conducted orientations in academic institutions, government agencies, and coastal barangays where implementation was underway. Consultative meetings were also held with fisherfolk and people’s organizations so climate-mitigation work would be rooted in actual community concerns rather than top-down messaging.',
                            'image' => '/images/imported/projects/legacy/4a.jpg',
                        ],
                        [
                            'slug' => 'mangrove-restoration-legislative-support',
                            'title' => 'Mangrove Restoration',
                            'category' => 'Policy and Restoration',
                            'year' => null,
                            'summary' => 'Barangay presentations and consultations were used to build legislative support for declaring mangrove areas as protected sites.',
                            'description' => 'One of the project’s objectives was to gather legislative backing for mangrove protection through ordinances and resolutions at the barangay level. PH Haiyan conducted barangay council presentations and consultations to help secure official support for the project and for local environmental protection. According to the original site, four barangays had already passed resolutions to protect mangrove plantation sites in their areas.',
                            'image' => '/images/imported/projects/legacy/4b.jpg',
                        ],
                        [
                            'slug' => 'regional-climate-change-conference-2016',
                            'title' => 'Hosting of Climate Change Conferences and Workshops',
                            'category' => 'Climate Education',
                            'year' => '2016',
                            'summary' => 'The first regional conference gathered cooperatives, LGUs, and national guests around climate change adaptation and mitigation.',
                            'description' => 'PH Haiyan’s first Regional Climate Change Conference was held on October 13 to 14, 2016. The event brought together cooperative groups and LGUs in Eastern Visayas and featured public figures and local leaders, including Senator Loren Legarda, Senator Cynthia Villar, Mayor Remedios Petilla of Palo, former Vice Governor Mimietta Bagulaya, and Tacloban City Councilor Jerry Yaokasin, among others.',
                            'image' => '/images/imported/projects/legacy/4c.jpg',
                        ],
                        [
                            'slug' => 'regional-climate-change-conference-2017',
                            'title' => 'Hosting of Climate Change Conferences and Workshops',
                            'category' => 'Youth Leadership',
                            'year' => '2017',
                            'summary' => 'The second conference focused on senior high and college students to raise youth awareness on climate change impacts and responses.',
                            'description' => 'The second Regional Climate Change Conference was held on November 20 to 21, 2017 in partnership with the Climate Change Commission. It brought together senior high and college students, together with teachers and administrators from 31 state universities and colleges in Region VIII. The conference aimed to help young people better understand the adverse effects of climate change and the interventions needed to mitigate and adapt to them.',
                            'image' => '/images/imported/projects/legacy/4d.jpg',
                        ],
                        [
                            'slug' => 'policy-initiatives',
                            'title' => '1. Policy Initiatives',
                            'category' => 'Policy Advocacy',
                            'year' => null,
                            'summary' => 'PH Haiyan supported climate-related ordinances, commemorative legislation, and proposals tied to local environmental governance.',
                            'description' => 'Beyond barangay-level advocacy, the project also participated in committee hearings, ordinance drafting, and lobbying with the Tacloban City Council. The original site notes that PH Haiyan helped push for city measures such as Climate Change Adaptation and Mitigation Week and November 8 as a Day of Remembrance and Gratitude in Tacloban City. It also mentions support for congressional efforts to declare November 8 as Yolanda Commemoration Day and work on a proposed Cancabato Bay Management Authority.',
                            'image' => '/images/imported/projects/legacy/p1.jpg',
                        ],
                        [
                            'slug' => 'reclaiming-the-beach-forest',
                            'title' => '2. Reclaiming the Beach Forest',
                            'category' => 'Coastal Protection',
                            'year' => null,
                            'summary' => 'An ongoing Barangay 88 initiative seeks to restore a beach forest that can serve both habitat protection and carbon absorption goals.',
                            'description' => 'The original site describes an ongoing initiative in Barangay 88 to create and develop a beach forest park that would serve as habitat for birds and other organisms while also helping absorb carbon dioxide. The project is framed as part of the country’s wider effort to secure buffer strips and protection zones along coastlines. It also links the initiative to existing forestry, water, climate, and disaster-risk laws intended to preserve greenbelt areas for ecological and public safety purposes.',
                            'image' => '/images/imported/projects/legacy/p2.jpg',
                        ],
                        [
                            'slug' => 'nursery-establishment-mangrove-and-beach-forest-species',
                            'title' => '3. Nursery Establishment for Mangrove and Beach Forest Species',
                            'category' => 'Nursery Development',
                            'year' => null,
                            'summary' => 'A nursery in Barangay 88 was established to maintain planting materials for mangrove and beach forest restoration.',
                            'description' => 'To support beach forest and mangrove planting sites, the project established a nursery in Barangay 88, San Jose, Tacloban City. According to the original site, the nursery maintains, protects, and prepares high-quality planting materials for both mangrove and beach forest species so restoration work can continue with a more reliable supply base.',
                            'image' => '/images/imported/projects/legacy/p3.jpg',
                        ],
                        [
                            'slug' => 'balugo-watershed-and-eco-tourism-park',
                            'title' => '4. Balugo Watershed and Eco-tourism Park in Barangay Salvacion',
                            'category' => 'Watershed Planning',
                            'year' => null,
                            'summary' => 'Technical studies were initiated for a watershed-based climate resiliency center and eco-tourism park in Barangay Salvacion.',
                            'description' => 'As recorded on the original website, technical studies and preparations were underway to develop a Climate Resiliency Center in Barangay Salvacion, Tacloban City. The 100-hectare site includes watershed and falls features, making it suitable for recreation and learning. The vision described by PH Haiyan includes a training and activity center with sleeping quarters, together with a living museum of Philippine flora and fauna and a venue for climate-related activities guided by a ridge-to-reef approach to climate proofing.',
                            'image' => '/images/imported/projects/legacy/p4.jpg',
                        ],
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'gallery',
                'title' => 'Gallery',
                'subtitle' => 'Photos from forums, inspections, tree-growing preparations, and public advocacy work.',
                'hero_eyebrow' => 'Gallery',
                'hero_title' => "A visual record of PH Haiyan's work in the field.",
                'hero_subtitle' => 'Browse images from flood-control forums, inter-agency meetings, site inspections, tree-growing activities, and community-facing campaigns.',
                'hero_image' => '/images/imported/gallery/joint-site-inspection.png',
                'meta_title' => 'Gallery | PH Haiyan Advocacy Inc.',
                'meta_description' => "View PH Haiyan's gallery of forums, inspections, campaigns, and community activities.",
                'content' => [
                    'intro' => "The gallery highlights PH Haiyan's public work on flood control, environmental advocacy, inter-agency coordination, tree-growing, and climate resilience activities in and around Tacloban City.",
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'forums',
                'title' => 'Forums',
                'subtitle' => 'Public discussion spaces focused on resilience, flood control, greening, and environmental governance.',
                'hero_eyebrow' => 'Forums',
                'hero_title' => 'Public conversations on flood control, greening, and local resilience.',
                'hero_subtitle' => "PH Haiyan's forum culture is built around practical dialogue, community experience, and issue-based discussion that can inform real action.",
                'hero_image' => '/images/imported/floodcontrol/flood-control-forum.jpg',
                'meta_title' => 'Forums | PH Haiyan Advocacy Inc.',
                'meta_description' => "Browse PH Haiyan's forum categories, featured discussions, and resilience-focused public topics.",
                'content' => [
                    'categories' => [
                        [
                            'title' => 'Flood Control and Mitigation',
                            'description' => 'Discussion on drainage, planning, mitigation priorities, and accountable flood-risk response in Tacloban.',
                        ],
                        [
                            'title' => 'Tree Planting and Greening',
                            'description' => 'Conversations on Adopt-a-Tree, Banaba planting, roadside greening, and long-term stewardship of planted areas.',
                        ],
                        [
                            'title' => 'Environmental Governance',
                            'description' => 'Topics focused on policy, legal compliance, agency coordination, and public-interest environmental questions.',
                        ],
                        [
                            'title' => 'Community Preparedness',
                            'description' => 'Stories and ideas about resilience education, citizen action, and practical preparedness at the community level.',
                        ],
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'letters',
                'title' => 'Letters',
                'subtitle' => 'Appeals, inquiries, and public correspondence tied to environmental protection and climate resilience.',
                'hero_eyebrow' => 'Public Correspondence',
                'hero_title' => 'Letters and public records that support accountable environmental action.',
                'hero_subtitle' => "This archive brings together PH Haiyan's appeals, inquiries, and issue-based letters on roads, trees, flood control, Cancabato Bay, and public-interest environmental governance.",
                'hero_image' => '/images/imported/news/official-statement.jpg',
                'meta_title' => 'Letters Archive | PH Haiyan Advocacy Inc.',
                'meta_description' => "Review PH Haiyan's letters, appeals, inquiries, and public-interest correspondence.",
                'content' => [
                    'intro' => "PH Haiyan's correspondence includes appeals to national agencies, inquiries on Cancabato Bay and watershed protection, flood-control letters, and documentation tied to the Adopt-a-Tree initiative along the Tacloban Bypass Road.",
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'contact',
                'title' => 'Contact',
                'subtitle' => 'Reach PH Haiyan for volunteer work, partnerships, media inquiries, or general concerns.',
                'hero_eyebrow' => 'Connect With Us',
                'hero_title' => "Let's work together for a greener, safer, more resilient Tacloban.",
                'hero_subtitle' => 'Reach PH Haiyan for volunteer coordination, partnership conversations, advocacy questions, or support for climate-resilience initiatives.',
                'hero_image' => '/images/imported/gallery/first-interagency-meeting.jpg',
                'meta_title' => 'Contact | PH Haiyan Advocacy Inc.',
                'meta_description' => 'Contact PH Haiyan Advocacy Inc. for volunteer, partnership, support, or general inquiries.',
                'content' => [
                    'intro' => 'Use this page to contact PH Haiyan about volunteer opportunities, partnerships, environmental advocacy concerns, media requests, or support for current initiatives.',
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'support',
                'title' => 'Support the Mission',
                'subtitle' => "Ways to stand with PH Haiyan's climate-resilience and environmental advocacy work.",
                'hero_eyebrow' => 'Support',
                'hero_title' => 'Support the people, programs, and public action behind resilience work.',
                'hero_subtitle' => 'Every contribution helps PH Haiyan keep tree-growing, forums, public letters, environmental campaigns, and citizen-centered climate advocacy moving.',
                'hero_image' => '/images/imported/news/adopt-a-tree.png',
                'meta_title' => 'Support the Mission | PH Haiyan Advocacy Inc.',
                'meta_description' => 'Learn how to donate, volunteer, or partner with PH Haiyan Advocacy Inc.',
                'content' => [
                    'benefits' => [
                        'Help sustain Adopt-a-Tree, roadside greening, mangrove work, and other tree-growing initiatives.',
                        'Support flood-control forums, public-awareness efforts, and environmental education in Tacloban and Eastern Visayas.',
                        'Strengthen issue-based letters, research, documentation, and citizen engagement on public-interest environmental concerns.',
                    ],
                ],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'news',
                'title' => 'News and Updates',
                'subtitle' => "Announcements, issue updates, and field stories from PH Haiyan's public work.",
                'hero_eyebrow' => 'News Archive',
                'hero_title' => 'Updates from campaigns, correspondence, field activities, and public events.',
                'hero_subtitle' => "Follow PH Haiyan's latest statements, issue campaigns, tree-growing updates, and resilience-focused public advocacy.",
                'hero_image' => '/images/imported/news/policy-reform.png',
                'meta_title' => 'News and Updates | PH Haiyan Advocacy Inc.',
                'meta_description' => 'Browse recent news and updates from PH Haiyan Advocacy Inc.',
                'content' => [],
                'is_published' => true,
                'published_at' => now(),
            ],
            [
                'slug' => 'events',
                'title' => 'Events',
                'subtitle' => "Forums, meetings, and public activities connected to PH Haiyan's advocacy work.",
                'hero_eyebrow' => 'Events',
                'hero_title' => 'A record of gatherings, forums, and issue-based public action.',
                'hero_subtitle' => "This archive highlights the meetings, forums, and field activities that have shaped PH Haiyan's environmental and resilience advocacy.",
                'hero_image' => '/images/imported/floodcontrol/building-resilience.jpg',
                'meta_title' => 'Events | PH Haiyan Advocacy Inc.',
                'meta_description' => "View PH Haiyan's forums, meetings, and public activities.",
                'content' => [],
                'is_published' => true,
                'published_at' => now(),
            ],
        ];

        foreach ($pages as $page) {
            Page::query()->updateOrCreate(
                ['slug' => $page['slug']],
                $page,
            );
        }
    }
}
